### ISSUE TITLE
Loading...

### ISSUE THREAD

**Issue by lakereef** [iulian-radu-at/find-unused-exports#9] opened 2021-06-04 18:39 UTC
Installed and opened the 'Unused Export' left panel and it just shows the blue progress bar continually at the top for over a half hour now.

**Comment by iulianraduat** [comment] 2021-06-06 21:28
Please install at least the version 1.8.0 and see if the problem is still there.
I found a regular expression where a \s* instead of a \s+ killed all the performance in certain cases.
Now each step also reports how much time it used.

**Comment by iulianraduat** [comment] 2021-07-26 11:46
Closed as the reporter not replayed.

**Closed as completed by iulianraduat** 2021-07-26 11:46 UTC
