### ISSUE TITLE
Breaking VSCode 

### ISSUE THREAD

**Issue by JoshShearer** [iulian-radu-at/find-unused-exports#24] opened 2023-04-18 15:13 UTC
Type: <b>Bug</b>

This extension is causing VSCode to restart all extensions repeatedly

Extension version: 1.20.0
VS Code version: Code 1.77.3 (704ed70d4fd1c6bd6342c436f1ede30d1cff4710, 2023-04-12T09:16:52.732Z)
OS version: Linux x64 5.19.0-35-generic
Modes:
Sandboxed: No
Remote OS version: Linux arm 6.1.21-v8+

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|AMD Ryzen Threadripper 1920X 12-Core Processor (24 x 3362)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>video_encode: disabled_software<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|3, 2, 1|
|Memory (System)|46.99GB (33.53GB free)|
|Process Argv|--unity-launch --crash-reporter-id 6c6849c8-f93a-4597-83f6-4dc0f0fb4fba|
|Screen Reader|no|
|VM|0%|
|DESKTOP_SESSION|ubuntu|
|XDG_CURRENT_DESKTOP|Unity|
|XDG_SESSION_DESKTOP|ubuntu|
|XDG_SESSION_TYPE|x11|

|Item|Value|
|---|---|
|Remote|SSH: lsshroomerydemo-ssh.at.remote.it|
|OS|Linux arm 6.1.21-v8+|
|CPUs|unknown (4 x 1500)|
|Memory (System)|1.76GB (1.28GB free)|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vslsvsres303:30308271
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vsclangdc:30486549
c4g48928:30535728
dsvsc012cf:30540253
pynewext54:30695312
azure-dev_surveyone:30548225
nodejswelcome1cf:30587006
3biah626:30602489
pyind779:30671433
89544117:30613380
pythonsymbol12:30671437
defaultazurewalk:30687958
pythonms35:30701012
pythonfmttext:30716742

```

</details>

**Comment by iulianraduat** [comment] 2023-04-18 15:42
Hi @JoshShearer,

According to https://github.com/microsoft/vscode/issues/176611#issuecomment-1469828906 it can be "an out of memory issue".

When it is happening?
* When you open a project as folder, open a workspace, open VSCode without any file?
* When you start the VSCode or when you navigate to the extension view?
* For all projects or only some?

Thanks,
Iulian

**Comment by iulianraduat** [comment] 2023-04-27 06:30
Is it possible this to be a duplicate of https://github.com/iulian-radu-at/find-unused-exports/issues/25?

**Comment by iulianraduat** [comment] 2023-05-07 18:09
Please check https://github.com/iulian-radu-at/find-unused-exports/issues/25#issuecomment-1537507541.

Thanks,
Iulian

**Comment by iulianraduat** [comment] 2023-05-10 08:48
Closed as it is a duplicate of [other issue](https://github.com/iulian-radu-at/find-unused-exports/issues/25) and version 1.21.1 can provide a fix for this problem.

**Closed as completed by iulianraduat** 2023-05-10 08:48 UTC
