### ISSUE TITLE
EISDIR: illegal operation on a directory, read

### ISSUE THREAD

**Issue by omidmafi** [iulian-radu-at/find-unused-exports#2] opened 2021-01-24 14:38 UTC
I receive this error when I hit refresh in the Unused Exports panel: 
**EISDIR: illegal operation on a directory, read**

Can I find a log file somewhere to see the error detail?

**Comment by iulianraduat** [comment] 2021-01-24 19:53
Hi @omidmafi,
You can enable the loggin in prefferences: findUnusedExports.debug
Most likely the plugin tries to read from a folder in your project but the access rights of it forbid the read or the access for your user.
I think that the same should happen for your user too. You can try do to a 'ls -Rl' and see if you get an error for any folder. If yes, it looks like you found the culpit.
Cheers,
Iulian

**Comment by omidmafi** [comment] 2021-01-26 21:44
Thanks Iulian,
The output panel for the extension shows a couple of informational messages but there is no error in there.
Also 'ls -Rl' does not fail with an error.
I am on macOS Bug Sur. I tried the same source code on a Windows machine and it works fine.
If this happened to someone else then it might be a bug that is worth investigating.

Thanks again.

**Comment by iulianraduat** [comment] 2021-01-27 10:02
Hi @omidmafi,
Can you check if you have any symlinked folder on MacOS? I think that maybe this is the problem.
A future version of the extension will try to log also this kind of errors.
Thanks,
Iulian

**Comment by omidmafi** [comment] 2021-01-29 01:54
Hi @iulian-radu-at 
I don't think so. The output of "ls -lR | grep ^l" in the source code folder is empty.
Thanks again!

**Comment by iulianraduat** [comment] 2021-02-03 08:35
Hi @omidmafi,

I found that "EISDIR: illegal operation on a directory, read" means that the extension tries to read from a folder as it is a file (https://stackoverflow.com/a/42677294/15051183).

Can you please find in the log (from output window) on which file/folder this happens? I try to figure out when this happens. Most likely when I try to "guess" the file name by adding .ts or .js or /index.js to an import path.

Cheers,
Iulian

**Comment by omidmafi** [comment] 2021-02-08 00:31
Sorry for the late reply, I missed your message.
That error is no longer happening. I've updated vscode and some dependencies inside my project a few days ago. Hard to tell if any of them had an impact on this issue. 
Thanks!

**Comment by iulianraduat** [comment] 2021-02-08 09:30
Thanks @omidmafi,
I will close it and if it happens again maybe we can get more data helping to identify the cause.
Cheers,
Iulian

**Closed as completed by iulianraduat** 2021-02-08 09:30 UTC

**Comment by iulianraduat** [comment] 2021-02-15 18:24
Hi @omidmafi,

As suspected, the crash was produced by folders having .js or .ts as extension.
The fix was published in 1.4.2

Cheers,
Iulian
