### ISSUE TITLE
Cannot read property 'charAt' of undefined

### ISSUE THREAD

**Issue by Escalion86** [iulian-radu-at/find-unused-exports#11] opened 2021-09-08 04:53 UTC
**Describe the bug**
Recive a message: Cannot read property 'charAt' of undefined

**Expected behavior**
Error on start working ext

**To Reproduce**
1. Start VS Code
2. Reload get same issue

**Information about the extension:**
 - Version: 1.10.0
 - Enabled features
   - [ - ] find unused exports
   - [ - ] find circular dependecies

**Information about your project:**
 - Type of files:
   - [ + ] .js / .jsx
   - [ - ] .ts / .tsx
 - [ - ] It has a tsconfig.json file 
 - Number of files
   - [ >100 ] .js / .jsx
   - [ 0 ] .ts / .tsx

**Screenshots**
![2021-09-08_11-48-07](https://user-images.githubusercontent.com/67676333/132448365-5b54206d-2f1f-4ee7-a57b-cfe2150cc031.png)
![2021-09-08_11-52-43](https://user-images.githubusercontent.com/67676333/132448517-1b3eda67-8ad5-4980-8ebf-ae93e81258f9.png)

**Comment by iulianraduat** [comment] 2021-09-08 11:01
Hi @Escalion86,

As there is no call off charAt() from my code, it must come from an included package.
Can you please see if you can find more information where it is happening?
For that you can check the Log Output windows, or open the Developers Tools (you find it in Help/Toggle Developer Tools) and check the console tab.

Thanks,
Iulian

**Comment by iulianraduat** [comment] 2021-09-26 09:30
Closed as there was no more input provided by the issuer.

**Comment by charles-stuart-appdetex** [comment] 2021-10-09 15:02
I saw the same issue.

```
workbench.desktop.main.js:768 TypeError: Cannot read property 'charAt' of undefined
	at w._processReaddir (vscode-file://vscode-app/Users/[username-removed]/.vscode/extensions/iulian-radu-at.find-unused-exports-1.10.0/out/main.js:6)
	at w._process (vscode-file://vscode-app/Users/[username-removed]/.vscode/extensions/iulian-radu-at.find-unused-exports-1.10.0/out/main.js:6)
	at new w (vscode-file://vscode-app/Users/[username-removed]/.vscode/extensions/iulian-radu-at.find-unused-exports-1.10.0/out/main.js:6)
	at Function.vr (vscode-file://vscode-app/Users/[username-removed]/.vscode/extensions/iulian-radu-at.find-unused-exports-1.10.0/out/main.js:5)
	at Or (vscode-file://vscode-app/Users/[username-removed]/.vscode/extensions/iulian-radu-at.find-unused-exports-1.10.0/out/main.js:9)
	at vscode-file://vscode-app/Users/[username-removed]/.vscode/extensions/iulian-radu-at.find-unused-exports-1.10.0/out/main.js:9
	at Array.map (<anonymous>)
	at vscode-file://vscode-app/Users/[username-removed]/.vscode/extensions/iulian-radu-at.find-unused-exports-1.10.0/out/main.js:9
	at Array.forEach (<anonymous>)
	at Sr (vscode-file://vscode-app/Users/[username-removed]/.vscode/extensions/iulian-radu-at.find-unused-exports-1.10.0/out/main.js:9)
	at zr (vscode-file://vscode-app/Users/[username-removed]/.vscode/extensions/iulian-radu-at.find-unused-exports-1.10.0/out/main.js:9)
	at ht.getFilesWithUnusedExports (vscode-file://vscode-app/Users/[username-removed]/.vscode/extensions/iulian-radu-at.find-unused-exports-1.10.0/out/main.js:9)
	at ht.filesWithUnusedExports (vscode-file://vscode-app/Users/[username-removed]/.vscode/extensions/iulian-radu-at.find-unused-exports-1.10.0/out/main.js:9)
	at ht.getChildren (vscode-file://vscode-app/Users/[username-removed]/.vscode/extensions/iulian-radu-at.find-unused-exports-1.10.0/out/main.js:9)
	at I.fetchChildrenNodes (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94)
	at I.getChildren (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94)
	at D.$getChildren (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94)
	at i._doInvokeHandler (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98)
	at i._invokeHandler (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98)
	at i._receiveRequest (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98)
	at i._receiveOneMessage (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98)
	at vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:98
	at a.fire (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66)
	at l.fire (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74)
	at vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113
	at a.fire (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66)
	at l.fire (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74)
	at u._receiveMessage (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74)
	at vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74
	at a.fire (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:66)
	at v.acceptChunk (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74)
	at vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:74
	at Socket.w (vscode-file://vscode-app/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:113)
	at Socket.emit (events.js:315)
	at addChunk (internal/streams/readable.js:309)
	at readableAddChunk (internal/streams/readable.js:284)
	at Socket.Readable.push (internal/streams/readable.js:223)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188)
onDidChangeNotification @ workbench.desktop.main.js:768
(anonymous) @ workbench.desktop.main.js:768
fire @ workbench.desktop.main.js:69
addNotification @ workbench.desktop.main.js:770
error @ workbench.desktop.main.js:1558
(anonymous) @ workbench.desktop.main.js:1498
processTicksAndRejections @ internal/process/task_queues.js:93
```

**Comment by iulianraduat** [comment] 2021-10-10 16:59
Hi @charles-stuart-appdetex,

I published version 1.10.1 with a try catch for this crash.
Please try it again in your code and let me know if the crash happens again and what is logged by this extension.

Thanks,
Iulian

**Comment by charles-stuart-appdetex** [comment] 2021-10-10 17:16
I'll try it out tomorrow. Thanks!

**Comment by iulianraduat** [comment] 2021-10-11 06:20
@charles-stuart-appdetex  please use version 1.10.2 as 1.10.1 is broken. Sorry

**Comment by charles-stuart-appdetex** [comment] 2021-10-11 13:50
It got further and then the extension host terminated. It's running in a pretty large project.

<img width="829" alt="image" src="https://user-images.githubusercontent.com/60156044/136800818-02d839e6-3579-4b20-9f3a-951edba0c673.png">

Another crash in a smaller project:

<img width="827" alt="image" src="https://user-images.githubusercontent.com/60156044/136801506-08e9ab5c-8710-426e-ac81-83ee5edba4e9.png">

I did confirm I'm running 1.10.2.

**Comment by iulianraduat** [comment] 2021-10-11 14:22
@charles-stuart-appdetex looks like we should do together a live meeting with screen sharing.
If you are allowed to do this and show me relevant parts, for debugging the extension, from your project, let me know.

I am locate in GMT+2h time zone. You? I can try to create a teams meeting were to join the two of us.

Waiting for your feedback.

Cheers,
Iulian

**Comment by iulianraduat** [comment] 2021-10-18 11:28
@charles-stuart-appdetex  it looks like you are not allowed to share the project so maybe you can provide other information so we can find why it is happening. Thanks

**Comment by VincentHokie** [comment] 2021-11-18 06:36
I'm also getting **Extension Host Terminated Unexpectedly** errors. Every time I "Restart Extension Host" it runs for 30 seconds and throws the error below

![Screenshot from 2021-11-18 09-36-11](https://user-images.githubusercontent.com/9318050/142364886-801d4a73-d7e8-4ef1-bdb7-5920d4eb8f67.png)

EDIT: This may actually be a different issue from what I see above. But do you know how I can resolve this? Should I open a seperate GH isse?

**Comment by iulianraduat** [comment] 2021-11-18 11:09
Hi @VincentHokie,

If you open the developer tools, can you find more information?

As long as I cannot reproduce it locally nor I have enough information about which chunk of code throws the error, I have no chance to fix it :(

Cheers,
Iulian

**Comment by VincentHokie** [comment] 2021-11-18 11:47
@iulian-radu-at here are some details

Here is the CPU profile generated (in the console log you can see a tmp profile created, this is it): 
[exthost-5241bb.zip](https://github.com/iulian-radu-at/find-unused-exports/files/7562455/exthost-5241bb.zip)

Here is the console with everything collapsed
![Screenshot from 2021-11-18 14-42-31](https://user-images.githubusercontent.com/9318050/142409601-56264c5f-10c5-48f3-8581-c79f16179f4a.png)

and here is the console with everything expanded
![Screenshot from 2021-11-18 14-43-57](https://user-images.githubusercontent.com/9318050/142409635-d2f14407-c236-4993-ada4-ad8cfab573c6.png)
![Screenshot from 2021-11-18 14-44-21](https://user-images.githubusercontent.com/9318050/142409651-53ea5e73-61ba-4a73-bdb4-4d329ddd81a4.png)
![Screenshot from 2021-11-18 14-44-33](https://user-images.githubusercontent.com/9318050/142409674-d2222595-72bf-4b91-9017-cdffc9b24025.png)

 I'll leave the console open for any debugging steps you have

**Comment by iulianraduat** [comment] 2022-02-04 17:04
Hi @charles-stuart-appdetex  and @VincentHokie,

Any news about your problem? Did you tried with a newer version?

Thanks for your help.

**Comment by VincentHokie** [comment] 2022-02-07 08:10
No news @iulian-radu-at , I tried to figure it out for a while but then moved on from it, unfortunately. I'll give a newer version a try soon and let you know

**Comment by iulianraduat** [comment] 2022-02-14 08:10
Hi @VincentHokie,

For v1.12.0 I made some changes to the code which affects also the scanning.
If you have time and you are in the mood, maybe you can try it again.

Thanks for your help,
Iulian

**Comment by iulianraduat** [comment] 2022-09-25 10:01
Closed as there is no activity in this ticket.

**Closed as completed by iulianraduat** 2022-09-25 10:01 UTC
